version: '3'
services:
    postgres:
        image: postgres:11
        container_name: nestjs-with-prisma
        restart: always
        environment:
            - POSTGRES_DB=nestjs-with-prisma
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=123456
        ports:
            - 5432:5432
